import Ember from 'ember';

import attr  from 'fireplace/model/attr';
import Model from 'fireplace/model/model';
import Store from 'fireplace/store';

import { makeSnapshot } from '../../helpers/firebase';

var get = Ember.get;
var set = Ember.set;

var Person;
var store;

module("Model - lifecycle properties", {
  setup: function() {
    Person = Model.extend({
      firstName: attr(),
      lastName:  attr()
    });
  }
});

test("isNew is true if the model has no snapshot", function() {
  var person = Person.create();

  ok(get(person, 'isNew'), "person is new");
  set(person, "snapshot", makeSnapshot("person", {first_name: "Bob", last_name: "Johnson"}));
  ok(!get(person, 'isNew'), "person is not new");
});


module("Model - ID", {
  setup: function() {
    store  = Store.create({firebaseRoot: "https://foo.firebaseio.com"});
    Person = Model.extend({
      name: attr()
    });
    Person.store = store;
  }
});

test("has a default ID generated by Firebase", function() {
  var person = Person.create({store: store});
  var id = get(person, "id");

  // mockfirebase makes IDs like "mock-1412972551247-6218"
  ok(id.match(/^mock-\d+-\d+$/), "ID should have been generated");
});

module("Model - store helpers", {
  setup: function() {
    Person = Model.extend({
      name: attr()
    });
  }
});

test("Model#save proxies through to the store", function() {
  expect(3);

  var person;
  var store = {
    saveRecord: function(object, key) {
      ok(true, "called store#saveRecord");
      equal(object, person, "passes object through to the store");
      equal(key, "name", "passes key through to the store");
    }
  };

  person = Person.create({store: store});
  person.save("name");
});

test("Model#update sets the value and saves", function() {
  expect(4);

  var person;
  var store = {
    saveRecord: function(object, key) {
      ok(true, "called store#saveRecord");
      equal(object, person, "passes object through to the store");
      equal(key, "name", "passes key through to the store");
    }
  };

  person = Person.create({store: store});
  person.update("name", "Bobby");
  equal(get(person, "name"), "Bobby", "has updated the name");
});

test("Model#delete proxies through to the store", function() {
  expect(2);

  var person;
  var store = {
    deleteRecord: function(object) {
      ok(true, "called store#deleteRecord");
      equal(object, person, "passes object through to the store");
    }
  };

  person = Person.create({store: store});
  person.delete();
});
